---
title: "Mini-Project 2"
author: "Your Name Here"
date: "March 24, 2017"
output: html_document
---

## Required libraries
```{r, message=FALSE}
library(dplyr)
library(ggplot2)
```

## Loading the data
```{r, include=FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

## Data wrangling
```{r}
library(dplyr)
```

Group by committee id and find average donation amt
```{r}
table1 <- contributions %>%
  group_by(cmte_id) %>%
  summarise(avg_contrib = mean(transaction_amt))
```

Select specific variables from committees
```{r}
table2 <- committees %>%
  select(cmte_id, cmte_name, tres_name, cmte_state, cmte_party_affiliation, connected_org_name)
```

```{r}
ourtable <- table2 %>%
  full_join(table1, by = "cmte_id")
glimpse(ourtable)
```

Get rid of NAs
```{r}
newTable <- na.omit(ourtable)
glimpse(newTable)
```


```{r}
stateTable <- newTable%>%
  group_by(cmte_state)%>%
  summarise(stateAverage = mean(avg_contrib))%>%
  filter(cmte_state != "GU") %>%
  filter(cmte_state != "PR") %>%
  filter(cmte_state != "MP") %>%
  filter(cmte_state != "VI") %>%
  arrange(desc(stateAverage))
  
```

```{r}
ggplot(stateTable, aes(x = reorder(cmte_state, stateAverage), y = stateAverage)) + geom_bar(stat = "identity") + coord_flip() 
```

A pipeline to find mean contributions by party affiliation in NY
```{r}
ourtable %>%
  select(Party = cmte_party_affiliation, State = cmte_state, Donations = avg_contrib) %>%
  group_by(Party) %>%
  filter(State == "NY") %>%
  summarise(AvgDonations = mean(Donations))
```

```{r}
stateTable <- newTable%>%
  group_by(cmte_state)%>%
  summarise(stateAverage = mean(avg_contrib))%>%
  filter(cmte_state != "GU") %>%
  filter(cmte_state != "PR") %>%
  filter(cmte_state != "MP") %>%
  filter(cmte_state != "VI") %>%
  arrange(desc(stateAverage))

```

```{r}
ggplot(stateTable, aes(x = reorder(cmte_state, stateAverage), y = stateAverage)) + geom_bar(stat = "identity") + coord_flip()
```
